#server:
#  port: 0 #9100

#management:
#  server:
#    port: 0 #"1${server.port}"

spring:
  datasource:
    url: "jdbc:postgresql://${POSTGRES_PORT_5432_TCP_ADDR:localhost}:${POSTGRES_PORT_5432_TCP_PORT:5432}/${POSTGRES_DB:warehouse}"
    username: "${POSTGRES_USER:postgres}"
    password: "${POSTGRES_PASSWORD:sprio}"
  jpa:
    hibernate:
      ddl-auto: "none"

---
spring:
  cloud:
    stream:
      bindings:
        stockUpdate:
          group: "warehouse"
      rabbit:
        bindings:
          stockUpdate:
            consumer:
              durableSubscribtion: true
              autoBindDlq: true
              requeueRejected: true
              republishToDlq: true
